StorefrontLab/Controllers/ManufacturersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StorefrontLab.Data.EF;
using PagedList.Mvc;
using PagedList;

namespace StorefrontLab.Controllers
{
    public class ManufacturersController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Manufacturers
        public ViewResult Index(int page =1)
        {
            int pageSize = 3;

            var manufacturers = db.Manufacturers.OrderBy(x => x.ManufacturerName).ToList();
            return View(manufacturers.ToPagedList(page, pageSize));
        }

        // GET: Manufacturers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            if (manufacturer == null)
            {
                return HttpNotFound();
            }
            return View(manufacturer);
        }

        // GET: Manufacturers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Manufacturers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]                                          //***LOGO added to database***
        public ActionResult Create([Bind(Include = "ManufacturerID,ManufacturerName,Logo,City,State,Country,Warranty")] Manufacturer manufacturer,
            HttpPostedFileBase logo)
        {
            #region FileUpload
            if (ModelState.IsValid)
            {
                string imgName = "noImage.jpg";
                if (logo != null)
                {
                    //get image and assign it to the variable
                    imgName = logo.FileName;

                    //declare and assign ext value from the substring where it will grab after the .
                    string ext = imgName.Substring(imgName.LastIndexOf("."));

                    //make a list of image extensions we will accept here
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (goodExts.Contains(ext.ToLower())&& (logo.ContentLength <= 4194304))//this is .net 4mb amx
                    {
                        //if it is ok and the extension is in the list we want to rename it with a guid (global unique id)
                        imgName = Guid.NewGuid() + ext;

                        //save it to the webserver
                        logo.SaveAs(Server.MapPath("~Content/images/" + "imgName"));
                    } else
                    {
                        imgName = "noImage.jpg";
                    }
                }
                //no matter which way that ended up we need to add the name to the object
                manufacturer.Logo = imgName;
                #endregion
                db.Manufacturers.Add(manufacturer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(manufacturer);
        }

        // GET: Manufacturers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            if (manufacturer == null)
            {
                return HttpNotFound();
            }
            return View(manufacturer);
        }

        // POST: Manufacturers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]                                          //***Logo added***
        public ActionResult Edit([Bind(Include = "ManufacturerID,ManufacturerName,Logo,City,State,Country,Warranty")] Manufacturer manufacturer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(manufacturer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(manufacturer);
        }

        // GET: Manufacturers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            if (manufacturer == null)
            {
                return HttpNotFound();
            }
            return View(manufacturer);
        }

        // POST: Manufacturers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Manufacturer manufacturer = db.Manufacturers.Find(id);
            db.Manufacturers.Remove(manufacturer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StorefrontLab/Views/Manufacturers/Create.cshtml
@model StorefrontLab.Data.EF.Manufacturer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Manufacturers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div id="mainContentViews">

        <div id="productHeader">
            <h2 id="productHeaderLeft">
                @Html.LabelFor(model => model.ManufacturerName, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.ManufacturerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManufacturerName, "", new { @class = "text-danger" })
            </h2>
            <div id="productHeaderRight">

            </div>
            <div class="clearfix"></div>
        </div>

        <div id="productLeft">
            <p>
                <img src="~/Content/images/noImage.jpg" title="No Book Image" alt="default image" /><br />
                <input type="file" style="display:inline;" name="ImageUpload"/> <!--whatever you name the input has to match on the value accepted of the post action-->
                <br />
            </p>
        </div>
        <div id="productRight">
            <p>
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </p>
            <p>
                @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })

            </p>
            <p>
                @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </p>
            <p>
                @Html.LabelFor(model => model.Warranty, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Warranty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Warranty, "", new { @class = "text-danger" })

            </p>
        </div>
        <div class="clearfix"></div>
        <div id="bookFooter">
            <div id="productFooterLeft">
                @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-danger" })
            </div>
            <div id="productFooterRight">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StorefrontLab/Views/Manufacturers/Delete.cshtml
@model StorefrontLab.Data.EF.Manufacturer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div id="mainContentViews">
    <h4>Manufacturer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ManufacturerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManufacturerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Warranty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Warranty)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StorefrontLab/Views/Manufacturers/Details.cshtml
@model StorefrontLab.Data.EF.Manufacturer

@{
    ViewBag.Title = "Details";
}

<h2><strong>@ViewBag.Title</strong></h2>
<hr />
<div id="mainContentViews">
    <div id="productHeader">
        <div id="productHeaderLeft">
            <div>
                <h4>Add New Manufacturer!</h4>
            </div>
        </div>
        <div id="productHeaderRight">
            <div>

            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div id="productLeft">
        <p>
            <img src="~/Content/images/@Model.Logo" alt="@Model.ManufacturerName" />
        </p>

    </div>
    <div id="productRight">
        <p>
            Manufacturer Name:
            @Html.DisplayFor(model => model.ManufacturerName)
        </p>
        <p>
            City:
            @Html.DisplayFor(model => model.City)
        </p>
        <p>

            State:
            @Html.DisplayFor(model => model.State)
        </p>
        <p>
            Country:
            @Html.DisplayFor(model => model.Country)
        </p>
        <p>
            Warranty:
            @Html.DisplayFor(model => model.Warranty)
        </p>
    </div>
    <div class="clearfix"></div>
</div>
    @if (User.IsInRole("Admin"))
    {
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.ManufacturerID }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    }

StorefrontLab/Views/Manufacturers/Edit.cshtml
@model StorefrontLab.Data.EF.Manufacturer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Manufacturers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ManufacturerID)
    @Html.HiddenFor(model => model.Logo)
    
<div id="mainContentViews">
    <div id="productHeader">
        <div id="productHeaderRight">
            <div>
                @Html.LabelFor(model => model.ManufacturerName, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.ManufacturerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManufacturerName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div id="productLeft">
        <p>
            <img src="~/Content/images/@Model.Logo" alt="@Model.ManufacturerName" />
        </p>
    </div>
    <div id="productRight">
        <p>
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </p>
        <p>
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </p>
        <p>
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
        </p>
        <p>
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
        </p>
    </div>
    <div class="clearfix"></div>
    <div id="productFooter">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update Manufacturer" class="btn btn-default" />
        </div>
        <div class="clearfix"></div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StorefrontLab/Views/Manufacturers/Index - Copy.cshtml
@*@model IEnumerable<StorefrontLab.Data.EF.Manufacturer>*@
@model PagedList.IPagedList<StorefrontLab.Data.EF.Manufacturer>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Your Favorite Brands!";
}

<h2>Brands</h2>
<div id="productHeaderLeft">


    @if (User.IsInRole("Admin"))
    {
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
    }
</div>

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))

    @if (Model.Count == 0)
    {
        <p class="alert alert-warning">
            No results meet your criteria
        </p>
    }

    <div id="mainContentViews">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().Logo)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().ManufacturerName)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().City)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().State)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().Country)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstOrDefault().Warranty)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                                <img src="~/Content/images/@item.Logo" alt="Manufacturer Logo" title="@item.ManufacturerName" />
                        </td>
                        <td>
                            @Html.ActionLink(item.ManufacturerName, "Details", new { id = item.ManufacturerID })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.City)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.State)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Warranty)
                        </td>


                        @if (User.IsInRole("Admin"))
                        {
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.ManufacturerID }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.ManufacturerID })
                        </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>

StorefrontLab/Views/Manufacturers/Index.cshtml
@*@model IEnumerable<StorefrontLab.Data.EF.Manufacturer>*@
@model PagedList.IPagedList<StorefrontLab.Data.EF.Manufacturer>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Your Favorite Brands!";
}

<h2>Brands</h2>
<div id="productHeaderLeft">


    @if (User.IsInRole("Admin"))
    {
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
    }
</div>

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))

    @if (Model.Count == 0)
    {
        <p class="alert alert-warning">
            No results meet your criteria
        </p>
    }

    <div id="mainContentViews">
        @foreach (var item in Model)
        {

            <img src="~/Content/images/@item.Logo" alt="Manufacturer Logo" title="@item.ManufacturerName" />
            @Html.ActionLink(item.ManufacturerName, "Details", new { id = item.ManufacturerID })

            if (User.IsInRole("Admin"))
            {

            @Html.ActionLink("Edit", "Edit", new { id = item.ManufacturerID }) 
            @Html.ActionLink("Delete", "Delete", new { id = item.ManufacturerID })
        }
        }
    </div>