StorefrontLab/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity; //added for entity framework domain models
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StorefrontLab.Data.EF; //added for our database

using PagedList;
using PagedList.Mvc;

using StorefrontLab.Models;







namespace StorefrontLab.Controllers
{
    public class CategoriesController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        //GET: Categories
        //public ActionResult Index()
        //{
        //    return View(db.Categories.ToList());
        //}

        public ViewResult Index(int page = 1)
        {
            int pageSize = 5;
            var categories = db.Categories.OrderBy(c => c.Name).ToList();

            //if(searchString != null)
            //{
            //    page = 1;
            //}
            //else
            //{
            //    searchString = currentFilter;
            //}
            //if (!String.IsNullOrEmpty(searchString)){

            //    categories = (from c in categories
            //                  where c.Name.ToUpper().Contains(searchString.ToUpper())
            //                  orderby c.Name
            //                  select c).ToList();
            //}
            //ViewBag.CurrentFilter = searchString;

            return View(categories.ToPagedList(page, pageSize));
        }

         



        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,Name,Comments")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,Name,Comments")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StorefrontLab/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StorefrontLab.Data.EF;
using PagedList;
using PagedList.Mvc;

using StorefrontLab.Models;

namespace StorefrontLab.Controllers
{
    public class ProductsController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        #region AJAX Delete
        [HttpPost]
        public JsonResult AjaxDelete(int id)
        {
            //retrieve the product from the data base
            Product productToBeRemoved = db.Products.Find(id);

            //remove said product
            db.Products.Remove(productToBeRemoved);

            //save the changes
            db.SaveChanges();

            //Create message to send back to UI as a JSON result also what is json
            var message = $"Deleted Product {productToBeRemoved.ProductName} from the database!";
            return Json(
                new
                {
                    id = id,
                    message = message
                });
        }
        #endregion

        //#region AJAX Create
        ////Add Publisher to the database via AJAX and return results
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public JsonResult ProductCreate(Product product)
        //{
        //    db.Products.Add(product);
        //    db.SaveChanges();

        //    return Json(product);
        //}

        //#endregion

        #region Ajax edit get and post

        [HttpGet]
        public PartialViewResult ProductEdit(int id)
        {
            Product pro = db.Products.Find(id);
            return PartialView(pro);
        }
        
        [HttpPost]
        public JsonResult ProductEdit(Product pro)
        {
            db.Entry(pro).State = EntityState.Modified;
            db.SaveChanges();
            return Json(pro);

        }




        #endregion

        //#region AJAX Details
        //[HttpGet]
        //public PartialViewResult ProductDetails(int id)
        //{
        //    //Retrieve the product by it's id
        //    Product pro = db.Products.Find(id);
        //    //Return a partial lview to the browser with the publisher object
        //    return PartialView(pro);

        //    //Set up this view
        //    //1)right click and add a partial view
        //    //2) scaffold details
        //    //3)select partial view

        //}





//#endregion
        //// GET: Products
        //public ActionResult Index()
        //{
        //    var products = db.Products.Include(p => p.Category).Include(p => p.InventoryStatus).Include(p => p.Manufacturer);
        //    return View(db.Products.ToList());
        //}

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            ViewBag.InventoryStatusID = new SelectList(db.InventoryStatuses, "InventoryStatusID", "InventoryStatusName");
            ViewBag.ManufacturerID = new SelectList(db.Manufacturers, "ManufacturerID", "ManufacturerName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,ManufacturerID,InventoryStatusID,CategoryID,ProductName,Color,Description,SerialNumber,Price,ProductImage")]
        Product product, HttpPostedFileBase ImageUpload)
        {
            
            if (ModelState.IsValid)
            {
                //only process the file if all the other validation has passed (modelState.IsValid_
                #region File Upload
                //provide a default img incase the user doesn't provide one
                string imageName = "noImage.jpg";

                //check the input and process whether its value is !null
                if (ImageUpload != null)
                {
                    //get the file name and save it to variable
                    imageName = ImageUpload.FileName;

                    //use the file name and extract the extension and save it ot a variable (important for images and control of sizes)
                    string ext = imageName.Substring(imageName.LastIndexOf("."));//returns .png or .jpg

                    //create a list of expressions we will take
                    string[] goodExts = new string[] { ".jpeg", ".jpg", ".png", ".gif" };

                    //compare the extension to the list
                    if (goodExts.Contains(ext.ToLower()))
                    {
                        //here we rename the file (conventionally use a guid) could do other things but just try to make one work then worry about it
                        imageName = Guid.NewGuid() + ext;

                        //now save the image to the web server
                        ImageUpload.SaveAs(Server.MapPath("~/Content/images/" + imageName));
                    }
                    //if they give us an invalid extension we want to just display the default image
                    else
                    {
                        imageName = "noImage.jpg";
                    }//end if imageUpload !=null
                    //no matter which way it went, need to update the db with the correct imagename for the record
                    product.ProductImage = imageName;
                    #endregion
                    //sending the info to entity framework
                    db.Products.Add(product);
                    //save the changes to the db
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }



                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", product.CategoryID);
            ViewBag.InventoryStatusID = new SelectList(db.InventoryStatuses, "InventoryStatusID", "InventoryStatusName", product.InventoryStatusID);
            ViewBag.ManufacturerID = new SelectList(db.Manufacturers, "ManufacturerID", "ManufacturerName", product.ManufacturerID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", product.CategoryID);
            ViewBag.InventoryStatusID = new SelectList(db.InventoryStatuses, "InventoryStatusID", "InventoryStatusName", product.InventoryStatusID);
            ViewBag.ManufacturerID = new SelectList(db.Manufacturers, "ManufacturerID", "ManufacturerName", product.ManufacturerID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,ManufacturerID,InventoryStatusID,CategoryID,ProductName,Color,Description,SerialNumber,Price,ProductImage")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", product.CategoryID);
            ViewBag.InventoryStatusID = new SelectList(db.InventoryStatuses, "InventoryStatusID", "InventoryStatusName", product.InventoryStatusID);
            ViewBag.ManufacturerID = new SelectList(db.Manufacturers, "ManufacturerID", "ManufacturerName", product.ManufacturerID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //remove the original file from the edit view
           
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        //Server side filter action
        //public ActionResult ProductsQs(string productsFilter)

StorefrontLab/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StorefrontLab.Models; //what is happening here, this just links to the viewmodel? 

namespace StorefrontLab.Controllers
{
    public class ShoppingCartController : Controller
    {
        //Get Shopping Cart
        public ActionResult Index()
        {
            //create a local version of the shopping cart from the Session(global)version
            var shoppingCart = (Dictionary<int, ShoppingCartViewModel>)Session["cart"];

            // if the value is  null or the count is 0, create an empty instance and provide no cart items.
            if (shoppingCart == null || shoppingCart.Count == 0)
            {
                //new empty instance of the local shopping cart to pass to the view
                shoppingCart = new Dictionary<int, ShoppingCartViewModel>();
                ViewBag.Message = ("Your cart is empty");
                
            }
            else //if there is something in the cart
            {
                ViewBag.Message = null; //i think this means that we do not send a message at all **
            }
            return View(shoppingCart);
        }//end of shopping cart index action

        public ActionResult UpdateCart(int productId, int qty)
        {
            //get the cart from session and hold it in a dictionary 
            Dictionary<int, ShoppingCartViewModel> shoppingCart = (Dictionary<int, ShoppingCartViewModel>)Session["cart"];

            //update the cart locally - for the item that is selected (row that the update button was clicked in)

            if (qty > 0)
            {
                shoppingCart[productId].Qty = qty;
                //return the cart back to session for use
                Session["cart"] = shoppingCart;
            }
            else
            {
                ViewBag.Message("No items exist in your cart");
            }
            return RedirectToAction("Index");
        }//end of update cart action

        public ActionResult RemoveFromCart(int id)
        {
            //get the cart out of session
            Dictionary<int, ShoppingCartViewModel> shoppingCart = (Dictionary<int, ShoppingCartViewModel>)Session["cart"];

            //remove the items
            shoppingCart.Remove(id);
            //set up viewbag message for no results
            if(shoppingCart.Count == 0)
            {
                ViewBag.Message = ("There are no items in your cart.");

                //set the current global session to null
                Session["cart"] = null;
            }

            //reload the index
            return RedirectToAction("Index");
        }
    }
}

StorefrontLab/Views/Shared/OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @* ***********TEXT to Display, Action, ControllerName (without "controller") *@
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (User.IsInRole("Admin"))
                    {
                <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
            }


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StorefrontLab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicons -->
    <link href="~/Content/img/favicon.png" rel="icon">
    <link href="~/Content/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800|Roboto+Slab:400,300,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Montserrat:wght@500&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS File -->
    <link href="~/Content/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/animations.css" rel="stylesheet">

    <!-- Libraries CSS Files -->
    <link href="~/Content/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!--AJAX stylesheet-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/south-street/jquery-ui.css">
    <!-- Main Stylesheet File -->
    <link href="~/Content/css/style.css" rel="stylesheet">
    <link href="~/Content/css/colors/color-3498db.css" rel="stylesheet">
    <!--Added PagedList Stylesheet-->
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/CustomStyles.css" rel="stylesheet" />
    <!-- =======================================================
      Template Name: NewFirm
      Template URL: https://templatemag.com/newfirm-bootstrap-business-template/
      Author: TemplateMag.com
      License: https://templatemag.com/license/
    ======================================================= -->
</head>

<body>

    <!-- Fixed navbar -->

    <div class="container">
        <div class="row text-center">
            <a class="navbar-brand col-sm-12" href="#"><b>Crazy Eddie's</b> Guitar Shack</a>

            <div class="row">
                <ul class="nav navbar-nav  navbar-right navButtons btn-group">
                    <li><a href="@Url.Action("Index", "Home")" class="btn btn-default ">Home</a></li>
                    <li><a href="@Url.Action("Index", "Products")" class="btn btn-default">Products</a></li>
                    @*<li><a href="@Url.Action("Index", "Categories")" class="btn btn-default">Categories</a></li>*@
                    <li><a href="@Url.Action("Index", "Manufacturers")" class="btn btn-default">Brands</a></li>
                    <li><a href="@Url.Action("Contact", "Home")" class="btn btn-default">Contact</a></li>
                    @Html.Partial("_LoginPartial")
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin", null, new { @class = "btn btn-default" })</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin", null, new { @class = "btn btn-default" })</li>
                    }
                     @if (Session["cart"] != null)
                    {
                        //total qty of the items that are currently in the session version of cart
                        var cart = (Dictionary<int, StorefrontLab.Models.ShoppingCartViewModel>)Session["cart"];
                        var cartCount = cart.Sum(x => x.Value.Qty);
                        <li>
                            <a href="@Url.Action("Index", "ShoppingCart")" class="btn btn-default">
                                <i class="fa fa-shopping-cart"></i>
                                <sup>
                                    <span class="cartCount">@cartCount</span>
                                </sup>
                            </a>

                        </li>
                    }

                </ul>
            </div>
        </div>
    </div>




    <!--Add this to render AJAX messages-->
    <div id="MessageDisplay" class="row">
        <div class="col-md col-md-offset1 text-center" id="MessageContent"></div>
    </div>
    <div id="mainContent">


        <div class="row">

        </div>

        @RenderBody()
    </div>

    <!-- FOOTER -->
    <div id="copyrights">
        <div class="container">
            <p>
                &copy;<strong>Jon M Boyce</strong> 2020
            </p>
            <div class="credits" style="opacity:.2;">
                Created with NewFirm template by <a href="https://templatemag.com/">TemplateMag</a>
            </div>
        </div>
    </div>

    <!-- JavaScript Libraries -->
    <script src="~/Content/lib/jquery/jquery.min.js"></script>
    <script src="~/Content/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/lib/php-mail-form/validate.js"></script>
    <script src="~/Content/lib/retina/retina.js"></script>
    <!-- Template Main Javascript File -->
    <script src="~/Content/js/main.js"></script>
    <!--add jquery ui cdn-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!--added jQuery AJAX CDN-->
    <script src="https://cdn.jsdelivr.net/jquery.ajax.unobtrusive/3.2.4/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("Scripts", false);


</body>
</html>